### ISSUE TITLE
Simplify the defaults for the typical case

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/nexus-sync-action#14]
It appears to be typical to use configuration like this:

```yml
url: ${{ env.OSSRH_URL }}
username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
create: true
upload: true
generate-checksums: true
upload-parallel: 10
close: true
release: true
```

The above can be seen in [@abilan's workflows](https://github.com/spring-io/spring-github-workflows/blob/81a6c3659be53643ae51660451db316dc75d36b0/.github/workflows/spring-artifactory-promote-central.yml#L68-L77). [Spring Shell](https://github.com/spring-projects/spring-shell/blob/c4e6cc97fdad6a2981cc4e33d5d303deb1db2799/.github/workflows/release-ga.yml#L175-L184) has very similar configuration as well.

#4 removed the need to configure the URL when using s01. Could similar updates to the other defaults be made as well? Specifically, I would welcome all of the following defaulting to `true`:

- `close`
- `create`
- `generate-checksums`
- `release`
- `upload`

Combined with #4, this would reduce the configuration above to the following:

```yml
username: ${{ secrets.OSSRH_S01_TOKEN_USERNAME }}
password: ${{ secrets.OSSRH_S01_TOKEN_PASSWORD }}
staging-profile-name: ${{ secrets.OSSRH_STAGING_PROFILE_NAME }}
upload-parallel: 10
```
